from collections.abc import Awaitable, Callable

from htmy.typing import Component, ComponentSequence, ComponentType, Context, Properties

def configure(
    safestr: type[object],
    xbool: type[object],
    formatter: type[object],
    xml_format_string: Callable[[str], str],
) -> None: ...
def format_name(name: str) -> str: ...
def xml_escape_text(s: str) -> str: ...
def quoteattr(s: str) -> str: ...
def format_attr(name: str, value: object) -> str: ...

class TagImpl:
    def __init__(
        self,
        name: str,
        props: Properties,
        children: ComponentSequence,
        child_separator: ComponentType,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def props(self) -> Properties: ...
    @property
    def children(self) -> ComponentSequence: ...
    @property
    def child_separator(self) -> ComponentType: ...
    def htmy(self, context: Context) -> Component: ...

class TagWithPropsImpl:
    def __init__(self, name: str, props: Properties) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def props(self) -> Properties: ...
    def htmy(self, context: Context) -> ComponentType: ...

class RenderSession:
    def __init__(
        self,
        component: Component,
        context: Context,
        string_formatter: Callable[[str], str],
    ) -> None: ...
    def pending(self) -> list[Awaitable[object]] | None: ...
    def submit(self, results: list[object]) -> list[Awaitable[object]] | None: ...
    def output(self) -> str: ...
    def cancel(self) -> None: ...
